name = "MathTeXEngine"
uuid = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
authors = ["Beno√Æt Richard <kolaru@hotmail.com>"]
version = "0.1.2"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AbstractTrees = "0.3"
Automa = "0.8"
DataStructures = "0.18"
FreeTypeAbstraction = "0.9"
GeometryBasics = "0.3"
LaTeXStrings = "1.2"
julia = "1.3"
